#!/bin/bash -e

PID_FILE="tmp/pids/server.pid"
if [ -f "$PID_FILE" ]; then
  rm -f "$PID_FILE"
fi

# Enable jemalloc for reduced memory usage and latency.
if [ -z "${LD_PRELOAD+x}" ]; then
    LD_PRELOAD=$(find /usr/lib -name libjemalloc.so.2 -print -quit)
    export LD_PRELOAD
fi

# If running the rails server then create or migrate existing database
if [ $# -ge 2 ] && [ "${@: -2:1}" = "./bin/rails" ] && [ "${@: -1:1}" = "server" ]; then
  ./bin/rails db:prepare
fi

# Default command if none given
if [ $# -eq 0 ]; then
  set -- bundle exec rails server -b 0.0.0.0
fi

exec "$@"
